version: "3"
services:
  postgres:
    image: postgres:11  
    ports:
      - "6008:5432"
    environment:
      POSTGRES_PASSWORD: max123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
